#!/bin/sh

# this script will publish and run the release version of the app
thisdir=$(cd $(dirname $0); pwd -P)
mydir=$(cd ${thisdir}/..; pwd -P)
echo "UAV BOT" > /proc/self/comm

cd "${thisdir}"/uav.bot
if dotnet publish -c Release -o "$mydir/release"; then
  cd "$mydir/release"
  dotnet uav.dll
else
  echo "Failed to build/publish"
fi
