#!/bin/sh

# this script will publish and run the release version of the app
mydir=$(cd $(dirname $0)/..; pwd -P)
echo "UAV BOT" > /proc/self/comm

if dotnet publish -c Release -o "$mydir/release"; then
  cd "$mydir/release"
  dotnet uav.dll
else
  echo "Failed to build/publish"
fi
