ALTER TABLE user_config ADD COLUMN credits_9 INT NOT NULL DEFAULT 0;
ALTER TABLE user_config ADD COLUMN credits_10 INT NOT NULL DEFAULT 0;
ALTER TABLE user_config ADD COLUMN credits_11 INT NOT NULL DEFAULT 0;
ALTER TABLE user_config ADD COLUMN credits_12 INT NOT NULL DEFAULT 0;
ALTER TABLE user_config ADD COLUMN credits_13 INT NOT NULL DEFAULT 0;
